// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0IkPldTr7grT0fe2baqzgkiF-pM8DZg',
    appId: '1:449922013506:web:4678578028f60e16c310db',
    messagingSenderId: '449922013506',
    projectId: 'andrews-b09c5',
    authDomain: 'andrews-b09c5.firebaseapp.com',
    storageBucket: 'andrews-b09c5.appspot.com',
    measurementId: 'G-QXGRYTFZ0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzL_1UjIfF7Q3vipxDeo10C-seuQocUg',
    appId: '1:449922013506:android:37ed3012ca89e713c310db',
    messagingSenderId: '449922013506',
    projectId: 'andrews-b09c5',
    storageBucket: 'andrews-b09c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Q15KWlDXA_fKC_UxGssYwnibB2BPOSQ',
    appId: '1:449922013506:ios:5da0ef1d0fa68205c310db',
    messagingSenderId: '449922013506',
    projectId: 'andrews-b09c5',
    storageBucket: 'andrews-b09c5.appspot.com',
    iosClientId: '449922013506-tmstk45o9hbnpujmbjcsma0ldcubmdkg.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Q15KWlDXA_fKC_UxGssYwnibB2BPOSQ',
    appId: '1:449922013506:ios:f39ca23920500575c310db',
    messagingSenderId: '449922013506',
    projectId: 'andrews-b09c5',
    storageBucket: 'andrews-b09c5.appspot.com',
    iosClientId: '449922013506-s9kd3s330e4vmjvsupjfgn299kg8g2iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameTemplate.RunnerTests',
  );
}
